version: "3.8"

services:
  routing:
    build: ./backend/routing
    container_name: routing
    ports:
      - "8000:8000"
    networks:
      - app-network

  everynoise-crawler:
    build: ./backend/everynoise-crawler
    container_name: everynoise-crawler
    ports:
      - "8001:8000"
    networks:
      - app-network

  spotify-api:
    build: ./backend/spotify-api
    container_name: spotify-api
    ports:
      - "8002:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - routing
      - everynoise-crawler
      - spotify-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
